import { chromium } from 'playwright-core';
import { readFileSync } from 'node:fs';
const out = process.argv[2];
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 400, height: 800 } });
const errs = [];
page.on('pageerror', (e) => errs.push(String(e).slice(0, 300)));
const frag = readFileSync('artifact/vizzio-3d-portfolio.html', 'utf8');
await page.setContent(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}</style></head><body>${frag}</body></html>`, { waitUntil: 'load' });
await page.waitForTimeout(800);
await page.click('#row-sg'); await page.waitForTimeout(400);
await page.click('#enter-country');
await page.waitForSelector('#take-off:not([disabled])', { timeout: 60000 });
await page.click('#take-off');
await page.waitForTimeout(1500);
const o1 = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
await page.screenshot({ path: `${out}/n-loading.png` });
await page.waitForSelector('.loading', { state: 'detached', timeout: 120000 });
await page.waitForTimeout(14000);
const o2 = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
await page.screenshot({ path: `${out}/n-city.png` });
console.log(JSON.stringify(await page.evaluate(() => { const q = (s) => { const e = document.querySelector(s); if (!e) return null; const r = e.getBoundingClientRect(); const c = getComputedStyle(e); return [Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height), c.opacity, c.display, c.position, c.zIndex]; }; const top = document.elementFromPoint(100, 150); const chain = []; for (let e = document.querySelector('.hud'); e; e = e.parentElement) { const c = getComputedStyle(e); chain.push([e.className || e.tagName, c.position, c.zIndex, c.transform, c.contain, c.containerType, c.overflow, c.visibility, c.clipPath]); } return { top: top?.className, chain, hud: q('.hud'), place: q('.hud-place'), main: q('.main--city'), app: q('.app'), cls: document.querySelector('.hud')?.className }; })));
await page.click('#change-flyer');
await page.waitForSelector('#take-off', { timeout: 20000 });
await page.click('#back-to-globe');
await page.waitForTimeout(800);
const back = await page.locator('.panel h2').textContent().catch(() => null);
console.log(JSON.stringify({ o1, o2, back, errs }));
await browser.close();
