import { chromium } from 'playwright-core';
import { readFileSync } from 'node:fs';
const frag = readFileSync('artifact/vizzio-3d-portfolio.html', 'utf8');
const page_html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>:root{color-scheme:light}body{margin:0;font:14px system-ui;background:#faf9f5}[hidden]{display:none!important}</style></head><body>${frag}</body></html>`;
const out = process.argv[2];
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const errors = [];
const page = await browser.newPage({ viewport: { width: 1440, height: 860 } });
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
page.on('pageerror', (e) => errors.push(String(e)));
await page.setContent(page_html, { waitUntil: 'load' });
await page.waitForTimeout(1800);
await page.screenshot({ path: `${out}/desk.png` });
await page.click('#row-sg');
await page.waitForTimeout(1800);
await page.screenshot({ path: `${out}/desk-panel.png` });
await page.click('#panel-close');
await page.hover('#row-sa');
await page.click('#row-sa');
await page.waitForTimeout(1600);
await page.screenshot({ path: `${out}/desk-soon.png` });
await page.setViewportSize({ width: 400, height: 800 });
await page.waitForTimeout(800);
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
await page.screenshot({ path: `${out}/phone.png`, fullPage: true });
console.log(JSON.stringify({ errors, overflow }));
await browser.close();
