import { chromium } from 'playwright-core';
import { readFileSync } from 'node:fs';
const out = process.argv[2];
const avatar = process.argv[3] ?? 'kite';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const logs = [];
const page = await browser.newPage({ viewport: { width: 1100, height: 660 } });
page.on('console', (m) => ['error', 'warning'].includes(m.type()) && logs.push(m.text().slice(0, 600)));
page.on('pageerror', (e) => logs.push('PAGEERROR ' + String(e).slice(0, 400)));
const frag = readFileSync('artifact/vizzio-3d-portfolio.html', 'utf8');
await page.setContent(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>:root{color-scheme:light}body{margin:0;font:14px system-ui;background:#faf9f5}[hidden]{display:none!important}</style></head><body>${frag}</body></html>`, { waitUntil: 'load' });
await page.waitForTimeout(800);
await page.click('#row-sg');
await page.waitForTimeout(400);
await page.click('#enter-country');
await page.waitForSelector('#take-off:not([disabled])', { timeout: 60000 });
await page.click('#avatar-' + avatar);
await page.waitForTimeout(600);
await page.click('#take-off');
await page.waitForTimeout(1800);
await page.screenshot({ path: `${out}/c-loading.png` });
await page.waitForSelector('.loading', { state: 'detached', timeout: 120000 });
await page.waitForTimeout(700);
await page.screenshot({ path: `${out}/c-intro.png` });
await page.waitForFunction(() => true, null, { timeout: 1000 });
// swiftshader is slow: wait for the intro to finish by watching the camera settle
await page.waitForTimeout(Number(process.argv[4] ?? 90000));
await page.screenshot({ path: `${out}/c-chase-${avatar}.png` });
const before = await page.textContent('.hud-flight .stat dd span');
await page.keyboard.down('KeyW');
await page.waitForTimeout(Number(process.argv[5] ?? 60000));
await page.screenshot({ path: `${out}/c-fly-${avatar}.png` });
const after = await page.textContent('.hud-flight .stat dd span');
await page.keyboard.up('KeyW');
console.log(JSON.stringify({ before, after }));
console.log(JSON.stringify(logs.filter((l) => !l.includes('ERR_TUNNEL') && !l.includes('THREE.Clock'))));
await browser.close();
